apiVersion: batch/v1
kind: Job
metadata:
  name: foodgendownload
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      schedulerName: volcano
      restartPolicy: Never
      volumes:
      - name: home
        persistentVolumeClaim:
          claimName: dokh-foodgen-pvc
      - name: data
        persistentVolumeClaim:
          claimName: dokh-foodgen-share-pvc
      containers:
      - name: download
        image: kohido/foodgen:v0.0.1
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: foodgen-secret
              key: GITHUB_TOKEN
        command: ["bash","-lc"]
        args:
        - |
            set -e
            df -h
            cd /mnt/data
            pip --version
            pip install pillow tqdm
            if [ ! -d "foodgen" ]; then
              git clone https://${GITHUB_TOKEN}@github.com/KhoiDOO/foodgen.git
            fi
            cd foodgen/data
            python3 download.py
        volumeMounts:
        - {name: home, mountPath: /workspace}
        - {name: data, mountPath: /mnt/data}
        resources:
          limits:   { nvidia.com/gpu: 2, cpu: "2",  memory: "8Gi" }
          requests: { nvidia.com/gpu: 2, cpu: "1",  memory: "6Gi" }