apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: foodgen-pipeline-
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: nvidia/cuda:12.9.1-cudnn-devel-ubuntu22.04
        command: [bash, -c]
        args:
          - |
            set -e
            apt-get update && \
            apt-get -y upgrade && \
            apt-get install -y --no-install-recommends \
                nano \
                curl \
                git \
                tmux \
                htop \
                nvtop \
                zlib1g \
                build-essential \
                software-properties-common \
                python3.10-dev && \
            rm -rf /var/lib/apt/lists/*
            git clone https://${TOKEN}@github.com/KhoiDOO/foodgen.git /foodgen
        env:
          - name: TOKEN
            valueFrom:
              secretKeyRef:
                name: github-token
                key: token
        workingDir: /foodgen