services:
  foodgen-train-vqganvae:
    build:
      context: .
      dockerfile: train_vqganvae.dockerfile
    image: foodgen:latest
    shm_size: '16g'
    volumes:
      - ./data:/git/foodgen/data  # Mount local data directory
      - ./outputs:/git/foodgen/outputs  # Mount local result directory
    environment:
      - WANDB_PROJECT_NAME=${WANDB_PROJECT_NAME}
      - WANDB_ENTITY=${WANDB_ENTITY}
      - WANDB_API_KEY=${WANDB_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  foodgen-download:
    build:
      context: .
      dockerfile: data.dockerfile
    image: foodgen:latest
    volumes:
      - ./data:/data  # Mount local data directory

networks:
  default:
    name: foodgen_network