services:
  foodgen-train:
    build:
      context: .
      dockerfile: train.dockerfile
    image: foodgen:latest
    volumes:
      - ./data:/git/foodgen/data  # Mount local data directory
      - ./output:/git/foodgen/output  # Mount local result directory
    environment:
      - token=${token}
      - WANDB_PROJECT_NAME=${WANDB_PROJECT_NAME}
      - WANDB_ENTITY=${WANDB_ENTITY}

  foodgen-download:
    build:
      context: .
      dockerfile: data.dockerfile
    image: foodgen:latest
    volumes:
      - ./data:/data  # Mount local data directory
    environment:
      - token=${token}

networks:
  default:
    name: foodgen_network